### PR TITLE
Implement Timeout for AuthenticateAsClientAsync

### PR DESCRIPTION
**Pull request by Kevin-Andrew**
See Issue #18. Implement a timeout wrapper around the call to the SslStream.AuthenticateAsClientAsync() because it doesn't take in a cancellation token itself. If the client attempts to connect to a server that does not implement TLS, a call to this method may wait forever because the server won't send back any data for the TLS handshake that this method is expecting. We'll use 100 seconds, which is the same as the default timeout for a WebRequest under a similar condition.

Here are the Unit Tests on Windows. Note, for testing I manually changed the hard coded timeout value to just 10 seconds.
image
And here are the tests on Ubuntu 20.
image

### CODE REVIEW

**Comment by colin-anderson** [comment]
Looks good, thanks!

We plan to add .NET 5 as a target framework soon, and I wonder if we might move this fix into an extension method at some point, keeping `SyslogTcpSink` at a higher level 🤔  Anyway, for now a colleague will also have a quick review and we can get this merged and released ASAP 👍

**Comment by colin-anderson** [comment]
I was just running the tests locally, and realised the reason the tests were taking so long was the 100s timeout. I realise it's the default `WebRequest` timeout, but I can't help feeling 100s is too long, especially so when running tests (for 3 frameworks, with .NET 5 added soon too). Maybe 30s, or even 10s is a "saner" default?

Alternatively, maybe we can make it configurable? If it's left at 100s, it's unlikely anyone will ever need to change it, except us for integration tests 😄  What do you think about having:

```c#
public class SyslogTcpSink : IBatchedLogEventSink, IDisposable
{
    ....
    public TimeSpan ConnectionTimeout { get; set; } = TimeSpan.FromSeconds(100);
    ....
}
```

That way we can adjust the timeout down during tests, and it also means users can change it on the off chance that they really need to.

**Comment by Kevin-Andrew** [comment]
I wouldn't want to go with a lower default because you can't predict someone's network connection. I considered exposing it as yet another property of the `SyslogTcpConfig`. I did not consider adding a read/write property directly to the `SyslogTcpSink` class because it doesn't have any others (there are two read-only properties) and you wouldn't have access to it if you use one of the `SyslogLoggerConfigurationExtensions` extension methods.

Do you want to add it to the `SyslogTcpConfig` instead.
image

**Comment by Kevin-Andrew** [comment]
How it would look for the Unit Test
image
image

**Comment by colin-anderson** [comment]
Yes, it does actually make more sense on `SyslogTcpConfig` - will try to get this merged later today!

**Pull request merged**
