### PR TITLE
Add hostName parameter to SyslogLoggerConfigurationExtensions

### PR DESCRIPTION
**Pull request by Osmodium**
For UdpSysLog and TcpSysLog where applicable.

### CODE REVIEW

**Comment by Osmodium** [comment]
@colin-anderson I'm not sure how you'd like the test of this to be performed. I did a quick glance at it and couldn't find a quick and fitting spot for it.

**Comment by colin-anderson** [comment]
We don't add tests for the extension methods, but I will go ahead and add another sample project that demonstrates using appsettings-based config (including this new param).

**Comment by Osmodium** [comment]
> We don't add tests for the extension methods, but I will go ahead and add another sample project that demonstrates using appsettings-based config (including this new param).

Okay I can respect that, and great with a new sample project, looks good! 👍

**Comment by Osmodium** [comment]
@colin-anderson has this been submitted to the NuGet package too?

**Comment by colin-anderson** [comment]
@Osmodium no, not yet. Note sure if we want to do a new release so soon after v2.0.5 for such a small changes - I need to check with a colleague on that.

In the meantime, if you want, you can workaround this by just copying the extension method into a CS file in your project.

**Comment by Osmodium** [comment]
> @Osmodium no, not yet. Note sure if we want to do a new release so soon after v2.0.5 for such a small changes - I need to check with a colleague on that.
> 
> In the meantime, if you want, you can workaround this by just copying the extension method into a CS file in your project.

This workaround doesn't seem to work when adding `SyslogMessages` through appconfig as far as I can conclude.

**Comment by colin-anderson** [comment]
@Osmodium 

It should work, as long as Serilog is able to find your extension method. You'll need to add the name of the assembly containing the extension method to the config, mind. E.g.:

```json
"Serilog": {
  "Using": ["MyAssembly"], <---- 👀
  "MinimumLevel": {
    "Default": "Information"
  },
  "WriteTo": [
    {
      "Name": "UdpSyslog",
...
```

**Comment by drdkcisc** [comment]
Ah, I wasn't aware that that was a possibility, thought it only looked within the same assembly as the implemented sink. Thanks, it works, however I'd still prefer it through the NuGet package, so I hope it will be out soon 😃

**Comment by Osmodium** [comment]
Ah, I wasn't aware that that was a possibility, thought it only looked within the same assembly as the implemented sink. Thanks, it works, however I'd still prefer it through the NuGet package, so I hope it will be out soon 😃

**Comment by colin-anderson** [comment]
@Osmodium just a quick note to say that v2.0.6 is released, which includes sourceHostOverride 👍

**Pull request merged**
