### PR TITLE
Replaced MessageTemplateTextFormatter with ITextFormatter to be able …

### PR DESCRIPTION
**Pull request by HrenuS**
Replaced MessageTemplateTextFormatter with ITextFormatter to be able to specify custom formatter for message text

### CODE REVIEW

**Comment by colin-anderson** [comment]
@Kevin-Andrew this looks straightforward enough to me - happy for me to go ahead and merge this?

**Review by Kevin-Andrew — APPROVED** [review]
Yup, looks good. Thanks, HrenuS.

**Comment by colin-anderson** [comment]
@HrenuS merged, thanks for your contribution!

I don't know when the next NuGet release will be, but likely within the next couple of weeks

**Comment by colin-anderson** [comment]
@CaringDev done! 🚀 https://www.nuget.org/packages/Serilog.Sinks.SyslogMessages/2.0.7

**Pull request merged**
