### PR TITLE
Ipv6 for udp

### PR DESCRIPTION
**Pull request by cantSleepNow**
Support ip v6 for UDP sink.

### CODE REVIEW

**Comment by colin-anderson** [comment]
Thanks for the contribution! Would you be able to add a simple test for this?

**Comment by cantSleepNow** [comment]
Hi Colin! You are welcome and thank you for the library! I'll delete this PR now since unit test is failing - seems local v6 cannot be assigned on travis, locally for me all tests are passing...

**Comment by colin-anderson** [comment]
No need to delete it, your tests look sound, it's just that the build environment being used at present in Travis doesn't support ipv6.

I'll see if it works on AppVeyor, and if we can do anything about Travis.

**Comment by colin-anderson** [comment]
So, Travis is only going to support IPV6 on their new container infrastructure, which at present only supports exotic CPU architectures, and AppVeyor doesn't support IPV6 at all.

I've also verified these tests pass when running locally, so I've added a commit to simply skip this test for now. When I get a chance, I'll add a new xUnit attribute to only skip it if IPV6 networking is not available.

Thanks again!

**Comment by colin-anderson** [comment]
Merged, will push a new version to NuGet in the next few days

**Comment by cantSleepNow** [comment]
Great! Thank you!

**Pull request merged**
